set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

find_program(CMAKE_C_COMPILER   x86_64-w64-mingw32-gcc    REQUIRED)
find_program(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++    REQUIRED)
find_program(CMAKE_RC_COMPILER  x86_64-w64-mingw32-windres REQUIRED)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
